$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: xsum
tags:
    model: "t5-large"
    seed: "1"
    batch_size: "128"
    deepspeed: "true"
    zero_offload: "none"
code:
    local_path: ../../src
command: >
    deepspeed trainer-wip.py 
    --deepspeed "./configs/ds_zero2.json" 
    --model_name_or_path "t5-large" 
    --config_name "./configs/t5-large-config.json" 
    --dataset_name "xsum" 
    --dataset_path {inputs.corpus} 
    --source_prefix "summarize: " 
    --max_source_length 512 
    --max_target_length 64 
    --fp16 True 
    --seed 1 
    --per_device_train_batch_size 8 
    --per_device_eval_batch_size 16 
    --gradient_accumulation_steps 1 
    --learning_rate 5e-5 
    --num_train_epochs 3.0 
    --logging_strategy "epoch" 
    --freeze_embeds False 
    --freeze_encoder False 
    --do_train 
    --do_eval 
    --do_predict 
    --save_strategy "no" 
    --predict_with_generate 
    --overwrite_output_dir 
    --output_dir "./outputs" 
    --logging_dir "./logs"
environment: azureml:hf-deepspeed:3
inputs:
    corpus:
        data: azureml:hf-xsum:1
        mode: download
compute:
    target: azureml:gpu-v100-8-lp
    instance_count: 1