$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: hf-tests
tags:
    model: "t5-3b"
    seed: "1"
    epoch: "3.0"
    learning_rate: "5e-5"
    batch_size: "64"
    deepspeed: "true"
    zero_offload: "cpu"
code:
    local_path: ../../src
command: >
    deepspeed trainer-wip.py 
    --deepspeed "./configs/ds_zero2.json" 
    --model_name_or_path "t5-large" 
    --dataset_name "samsum" 
    --dataset_path {inputs.corpus} 
    --source_prefix "summarize: " 
    --max_source_length 512 
    --max_target_length 90 
    --fp16 True 
    --seed 1 
    --per_device_train_batch_size 8 
    --per_device_eval_batch_size 8 
    --gradient_accumulation_steps 1 
    --learning_rate 5e-5 
    --num_train_epochs 3.0 
    --evaluation_strategy "epoch" 
    --logging_strategy "epoch" 
    --freeze_embeds False 
    --freeze_encoder False 
    --do_train 
    --do_predict 
    --predict_with_generate 
    --overwrite_output_dir 
    --output_dir "./outputs/hf-model" 
    --logging_dir "./logs"
environment: azureml:hf-deepspeed:2
inputs:
    corpus:
        data: azureml:hf-samsum:1
        mode: download
compute:
    target: azureml:gpu-v100-8-lp
    instance_count: 1