$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: hf-tests
tags:
    model: "pegasus-large"
    seed: "1"
    epoch: "3.0"
    learning_rate: "5e-5"
    batch_size: "64"
code:
    local_path: ../../src
command: >
    python trainer-wip.py 
    --model_name_or_path "google/pegasus-large" 
    --config_name "google/pegasus-xsum" 
    --dataset_name "samsum" 
    --dataset_path {inputs.corpus} 
    --max_source_length 512 
    --max_target_length 90 
    --ddp_find_unused_parameters False 
    --fp16 False 
    --seed 1 
    --per_device_train_batch_size 8 
    --per_device_eval_batch_size 8 
    --gradient_accumulation_steps 1 
    --learning_rate 5e-5 
    --adafactor True 
    --num_train_epochs 3.0 
    --evaluation_strategy "epoch" 
    --logging_strategy "epoch" 
    --do_train 
    --do_predict 
    --predict_with_generate 
    --overwrite_output_dir 
    --output_dir "./outputs/hf-model" 
    --logging_dir "./logs"
environment: azureml:hf-deepspeed:2
inputs:
    corpus:
        data: azureml:hf-samsum:1
        mode: download
compute:
    target: azureml:gpu-v100-8-lp
    instance_count: 1
distribution:
    type: pytorch
    process_count: 8