$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: samsum
tags:
    model: "distill-pegasus-16-8"
    seed: "1"
    batch_size: "256"
code:
    local_path: ../../src
command: >
    python trainer-wip.py 
    --model_name_or_path "sshleifer/distill-pegasus-xsum-16-8" 
    --dataset_name "samsum" 
    --dataset_path {inputs.corpus} 
    --max_source_length 512 
    --max_target_length 90 
    --ddp_find_unused_parameters False 
    --fp16 True 
    --adafactor True 
    --seed 1 
    --per_device_train_batch_size 16 
    --per_device_eval_batch_size 16 
    --gradient_accumulation_steps 1 
    --learning_rate 5e-5 
    --num_train_epochs 3.0 
    --weight_decay 0.01 
    --logging_strategy "epoch" 
    --freeze_embeds False 
    --freeze_encoder False 
    --do_train 
    --do_eval 
    --do_predict 
    --predict_with_generate 
    --overwrite_output_dir 
    --output_dir "./outputs" 
    --logging_dir "./logs" 
environment: azureml:hf-deepspeed:3
inputs:
    corpus:
        data: azureml:hf-samsum:1
        mode: download
compute:
    target: azureml:gpu-v100-8-lp
    instance_count: 1
distribution:
    type: pytorch
    process_count: 8