$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: cnn
tags:
    model: "bart-base"
    seed: "1"
    epoch: "0.1"
    learning_rate: "2e-5"
    batch_size: "256"
    deepspeed: "true"
    zero_offload: "false"
code:
    local_path: ../../src
command: >
    deepspeed trainer-wip.py 
    --deepspeed "./configs/ds_zero2.json" 
    --model_name_or_path "facebook/bart-base" 
    --config_name "./configs/bart-base-cnn.json" 
    --dataset_name "cnn" 
    --dataset_path {inputs.corpus} 
    --max_source_length 1024 
    --max_target_length 142 
    --fp16 True 
    --seed 1 
    --per_device_train_batch_size 32 
    --per_device_eval_batch_size 32 
    --gradient_accumulation_steps 1 
    --learning_rate 5e-5 
    --num_train_epochs 0.1 
    --do_train 
    --save_strategy "no" 
    --predict_with_generate 
    --overwrite_output_dir 
    --output_dir "./outputs" 
    --logging_dir "./logs"
environment: azureml:hf-deepspeed:3
inputs:
    corpus:
        data: azureml:hf-cnn:1
        mode: download
compute:
    target: azureml:gpu-v100-8-lp
    instance_count: 1