name: cli-pytorch-job
on:
  schedule:
    - cron: '0 20 * * 5'
  push:
    branches:
      - main
    paths:
      - examples/jobs/pytorch-job.yml
      - .github/workflows/cli-pytorch-job.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Setup CLI
      run: |
        az extension add -n ml -y
        az configure --defaults group="UW-Embeddings" workspace="TxtsumDemo"
      continue-on-error: true
      
    - name: Create job
      run: |
        run_id=$(az ml job create -f jobs/pytorch-job.yml --query name -o tsv)
        az ml job stream -n $run_id
        status=$(az ml job show -n $run_id --query status -o tsv)
        echo $status
        if [[ $status == "Completed" ]]
        then
          echo "Job completed"
        elif [[ $status ==  "Failed" ]]
        then
          echo "Job failed"
          exit 1
        else 
          echo "Job status not failed or completed"
          exit 2
        fi
      working-directory: examples
