name: ARM Quickstart
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/arm-cmd-job-pytorch.yml"
      - ".cloud/azuredeployCmdJobPytorch.json"
  workflow_dispatch:
jobs:
  fine-tune:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
        
      - name: Deploy ARM template
        run: |
          az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./azuredeployCmdJobPytorch.json --parameters workspaceName='${{secrets.AZUREML_WORKSPACE}}'
        working-directory: .cloud
