name: arm-cmd-job-pytorch
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/arm-cmd-job-pytorch.yml"
      - ".cloud/azuredeployCmdJobPytorch.json"
jobs:
  train-on-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy ARM Template
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: UW-Embeddings
          template: ./.cloud/azuredeployCmdJobPytorch.json
          parameters: ./.cloud/azuredeployCmdJobPytorch.parameters.json
