name: ARM Quickstart
on:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches:
      - main
    paths:
      - ".github/workflows/arm-cmd-job-pytorch.yml"
      - "cloud/quickstart/azuredeployCmdJobPytorch.json"
  workflow_dispatch:
jobs:
  fine-tune:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Deploy ARM template
        run: |
          az deployment group create --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --template-file ./azuredeployCmdJobPytorch.json --parameters workspaceName='${{secrets.AZUREML_WORKSPACE}}' location='${{secrets.AZUREML_LOCATION}}' jobName='${{github.RUN_ID}}' computePriority='Dedicated'
        working-directory: cloud/quickstart

      - name: Check ML job status
        run: |
          az ml job stream -n ${{github.RUN_ID}}
          status=$(az ml job show -n ${{github.RUN_ID}} --query status -o tsv)
          echo $status
          if [[ $status == "Completed" ]]
          then
            echo "Job completed"
          elif [[ $status ==  "Failed" ]]
          then
            echo "Job failed"
            exit 1
          else 
            echo "Job status not failed or completed"
            exit 2
          fi
