name: CLI DeepSpeed Job
on:
  schedule:
    - cron: '0 20 * * 5'
  push:
    branches:
      - main
    paths:
      - examples/jobs/deepspeed-job.yml
      - .github/workflows/cli-cmd-job-deepspeed.yml
  workflow_dispatch:
jobs:
  fine-tune:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2
      
    - name: Setup CLI defaults
      run: |
        az configure --defaults group="${{secrets.AZURE_RESOURCE_GROUP}}" workspace="${{secrets.AZUREML_WORKSPACE}}"
      continue-on-error: true
      
    - name: Create ML job
      run: |
        run_id=$(az ml job create -f jobs/deepspeed-job.yml --query name -o tsv)
        az ml job stream -n $run_id
        status=$(az ml job show -n $run_id --query status -o tsv)
        echo $status
        if [[ $status == "Completed" ]]
        then
          echo "Job completed"
        elif [[ $status ==  "Failed" ]]
        then
          echo "Job failed"
          exit 1
        else 
          echo "Job status not failed or completed"
          exit 2
        fi
      working-directory: examples
